require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mod_mail_messages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ModMailMessage. As you add validations to ModMailMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ModMailMessage.create! valid_attributes
      get mod_mail_messages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mod_mail_message = ModMailMessage.create! valid_attributes
      get mod_mail_message_url(mod_mail_message)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mod_mail_message_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mod_mail_message = ModMailMessage.create! valid_attributes
      get edit_mod_mail_message_url(mod_mail_message)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ModMailMessage" do
        expect {
          post mod_mail_messages_url, params: { mod_mail_message: valid_attributes }
        }.to change(ModMailMessage, :count).by(1)
      end

      it "redirects to the created mod_mail_message" do
        post mod_mail_messages_url, params: { mod_mail_message: valid_attributes }
        expect(response).to redirect_to(mod_mail_message_url(ModMailMessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ModMailMessage" do
        expect {
          post mod_mail_messages_url, params: { mod_mail_message: invalid_attributes }
        }.to change(ModMailMessage, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mod_mail_messages_url, params: { mod_mail_message: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mod_mail_message" do
        mod_mail_message = ModMailMessage.create! valid_attributes
        patch mod_mail_message_url(mod_mail_message), params: { mod_mail_message: new_attributes }
        mod_mail_message.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mod_mail_message" do
        mod_mail_message = ModMailMessage.create! valid_attributes
        patch mod_mail_message_url(mod_mail_message), params: { mod_mail_message: new_attributes }
        mod_mail_message.reload
        expect(response).to redirect_to(mod_mail_message_url(mod_mail_message))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mod_mail_message = ModMailMessage.create! valid_attributes
        patch mod_mail_message_url(mod_mail_message), params: { mod_mail_message: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mod_mail_message" do
      mod_mail_message = ModMailMessage.create! valid_attributes
      expect {
        delete mod_mail_message_url(mod_mail_message)
      }.to change(ModMailMessage, :count).by(-1)
    end

    it "redirects to the mod_mail_messages list" do
      mod_mail_message = ModMailMessage.create! valid_attributes
      delete mod_mail_message_url(mod_mail_message)
      expect(response).to redirect_to(mod_mail_messages_url)
    end
  end
end
